# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  # más tiempo para boot/SSH
  config.vm.boot_timeout = 600
  config.ssh.insert_key = false

  # VM 1: cliente
  config.vm.define :clienteUbuntu do |m|
    m.vm.box = "bento/ubuntu-22.04"
    m.vm.hostname = "clienteUbuntu"
    m.vm.network :private_network, ip: "192.168.100.2"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus   = 2
      vb.gui    = true
    end
  end

  # VM 2: servidor (Minikube)
  config.vm.define :servidorUbuntu do |m|
    m.vm.box = "bento/ubuntu-22.04"
    m.vm.hostname = "servidorUbuntu"
    m.vm.network :private_network, ip: "192.168.100.3"
    m.vm.provision "shell", path: "script.sh"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = 8192
      vb.cpus   = 4
      vb.gui    = true
    end
  end
end
