apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-classifier-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spam-classifier
  template:
    metadata:
      labels:
        app: spam-classifier
    spec:
      containers:
      - name: api
        image: local/clasificadorspam:1.0 
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: spam-classifier-svc
spec:
  selector:
    app: spam-classifier
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30082
